import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { UI_ASSETS } from "../src/assets.generated";

/**
 * Direct generated-asset check: the committed src/assets.generated.ts must
 * stay byte-for-byte current with the ui/ sources it embeds, and the module
 * must import/typecheck cleanly and export exactly the declared ui files.
 * Regenerate with `bun run assets:generate` after changing ui/ files.
 */

const gatewayRoot = resolve(import.meta.dir, "..");
const uiDir = join(gatewayRoot, "ui");
const generatedAssetPath = join(gatewayRoot, "src", "assets.generated.ts");

const ASSET_FILES = [
  "index.html",
  "styles.css",
  "app.js",
  "execution-proposal.js",
  "operational-semantics.js",
] as const;

/** Mirrors scripts/generate-ui-assets.ts so the check validates the real output. */
function escapeLiteral(content: string): string {
  return content.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");
}

function regeneratedAssetsSource(): string {
  const entries = ASSET_FILES.map((name) => {
    const content = readFileSync(join(uiDir, name), "utf8");
    return `  ${JSON.stringify(name)}: \`${escapeLiteral(content)}\`,`;
  });
  return [
    "// Generated by scripts/generate-ui-assets.ts — do not edit by hand.",
    "// Regenerate with `bun run assets:generate` after changing ui/ files.",
    "export const UI_ASSETS: Readonly<Record<string, string>> = {",
    entries.join("\n"),
    "};",
    "",
  ].join("\n");
}

describe("generated UI assets stay current", () => {
  test("the committed generated asset module is byte-for-byte current with the ui/ sources", () => {
    expect(readFileSync(generatedAssetPath, "utf8")).toBe(regeneratedAssetsSource());
  });

  test("the generated module exports exactly the declared ui files with their current content", () => {
    expect(Object.keys(UI_ASSETS)).toEqual([...ASSET_FILES]);
    for (const name of ASSET_FILES) {
      expect(UI_ASSETS[name]).toBe(readFileSync(join(uiDir, name), "utf8"));
    }
  });
});
