#!/usr/bin/env bun
/**
 * Regenerate src/ui/assets.generated.ts from the static UI files in ui/.
 *
 * The generated module embeds the UI assets as string constants so both the
 * source checkout and the compiled single-file binary can serve them without a
 * file-system dependency. Run `bun run assets:generate` after changing any
 * file under ui/ (the local build command does this automatically).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const gatewayRoot = resolve(import.meta.dir, "..");
const uiDir = join(gatewayRoot, "ui");
const outputPath = join(gatewayRoot, "src", "assets.generated.ts");

const ASSET_FILES = [
  "index.html",
  "styles.css",
  "app.js",
  "execution-proposal.js",
  "operational-semantics.js",
] as const;

function escapeLiteral(content: string): string {
  return content.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");
}

const entries = ASSET_FILES.map((name) => {
  const content = readFileSync(join(uiDir, name), "utf8");
  return `  ${JSON.stringify(name)}: \`${escapeLiteral(content)}\`,`;
});

const generated = `// Generated by scripts/generate-ui-assets.ts — do not edit by hand.
// Regenerate with \`bun run assets:generate\` after changing ui/ files.
export const UI_ASSETS: Readonly<Record<string, string>> = {
${entries.join("\n")}
};
`;

writeFileSync(outputPath, generated);
console.log(`wrote ${outputPath} (${ASSET_FILES.length} assets, ${generated.length} bytes)`);
